name: Daily Weather Bot

on:
  schedule:
    - cron: "0 17 * * 1"  # Monday 10:00 AM PT
    - cron: "0 16 * * 2"  # Tuesday 9:00 AM PT
    - cron: "0 16 * * 3"  # Wednesday 9:00 AM PT
    - cron: "0 16 * * 4"  # Thursday 9:00 AM PT
    - cron: "0 16 * * 5"  # Friday 9:00 AM PT
    - cron: "0 17 * * 6"  # Saturday 10:00 AM PT
    - cron: "0 17 * * 0"  # Sunday 10:00 AM PT
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run weather bot
      env:
        OWM_API_KEY: ${{ secrets.OPENWEATHER }}
        TWITTER_API_KEY: ${{ secrets.API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.API_KEY_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TWITTER_ACCESS_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      run: python weather_bot.py
